### ISSUE TITLE
issue with "open an issue link"

### ISSUE THREAD

**Issue by pineapples5972** [hDmtP/hdmtp.github.io#1]
this address is invalid "https://hdmtp.github.io/github.com/hdmtp/hdmtp.github.io/issues/new"

this is valid
https://github.com/hdmtp/hdmtp.github.io/issues/new

**Comment by pineapples5972** [comment]
![Screenshot_20220618_073629](https://user-images.githubusercontent.com/62638787/174418437-e86b8f71-f2a9-4438-bf8c-8b7dc32beb63.png)
This link is broken.

**Comment by hDmtP** [comment]
> ![Screenshot_20220618_073629](https://user-images.githubusercontent.com/62638787/174418437-e86b8f71-f2a9-4438-bf8c-8b7dc32beb63.png)
> This link is broken.

Fixed
