### ISSUE TITLE
Fix widening of Images 

### ISSUE THREAD

**Issue by pineapples5972** [hDmtP/hdmtp.github.io#2]
Setting fixed size for img element messed the dimension of all images. 
```
img {
    width: 300px;
    height: 180px;
    margin: auto;
}
```

Use percentage instead 
```
img {
max-width: 100%;
height: auto;
}
```

**Comment by hDmtP** [comment]
Hey, thanks for opening the first ever issue on this repo. But I kinda don't like how the imgs are taking the whole screen. That's why I had decided to fix its `height` and `width`.

**Comment by pineapples5972** [comment]
set auto for height and 30% or 40% to width
This way images wont take whole screen.
```
img { width: 30%;
         height: auto;
}
```

**Comment by pineapples5972** [comment]
Also wrap caption of images into `<figcaption>` tags.
set css of figcaption to 

```
figcaption {
    margin: 0.8em 0 0 0;
    opacity: .7;
}
```
To make caption fit below of image. and nice opacity to distinguish them from regular text.

**Comment by hDmtP** [comment]
> Also wrap caption of images into `<figcaption>` tags.
> set css of figcaption to 
> 
> ```
> figcaption {
>     margin: 0.8em 0 0 0;
>     opacity: .7;
> }
> ```
> To make caption fit below of image. and nice opacity to distinguish them from regular text.


That's a good idea 💡. Thanks for that.

**Comment by hDmtP** [comment]
> set auto for height and 30% or 40% to width
> This way images wont take whole screen.
> ```
> img { width: 30%;
>          height: auto;
> }
> ```

I will tweak around a bit regarding the `img` tag and will see what suits the best.
